#!/usr/bin/env bash

set -e

# Establish file names
FILE="list.txt"
TMPFILE=$(mktemp)

# Preserve GUIDE
grep '^#' "$FILE" > "$TMPFILE"

# Blank line after GUIDE
echo "" >> "$TMPFILE"

# Sort /@ entries
grep '^/@' "$FILE" | sort -u >> "$TMPFILE"

# Sort /channel entries
grep '^/channel/' "$FILE" | sort -u >> "$TMPFILE"

# Replace original file
mv "$TMPFILE" "$FILE"
