name: Channel Appeal
description: Appeal a Channel on the Blocklist
title: "[Channel Appeal] "
labels: Appeal
body:
  - type: textarea
    id: links
    attributes:
      label: Channel Links
      description: Paste all relevant links below. You can paste multiple links.  
                   Each link should be on its own line.
      placeholder: "https://example.com/1\nhttps://example.com/2\nhttps://example.com/3"
